<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Sabre\DAV\Client;
use Sabre\HTTP\ClientHttpException;

$url = 'https://localhost:9200/remote.php/webdav/';
$accessToken = 'eyJhbGciOiJQUzI1NiIsImtpZCI6InByaXZhdGUta2V5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJ4ZFhPdDEzSkt4eW0xQjFRY0VuY2YyWERrTEFleE1CRndpVDlqNkVmaGhIRkpoczJLTTlqYmpUbWY4SkJYRTY5IiwiZXhwIjoxNjkwMTk0NzExLCJpYXQiOjE2OTAxOTQ0MTEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJqdGkiOiJKOGRaNHczWVpsdVo3S0hvbVUyWmx1ODZ6QU1mUXg3MSIsImxnLmkiOnsiZG4iOiJBZG1pbiIsImlkIjoib3duQ2xvdWRVVUlEPTFjMjBlNmFlLTY2NWUtNDZlZi1iMzg0LTU5ZjYzYTkwYjU0ZiIsInVuIjoiYWRtaW4ifSwibGcucCI6ImlkZW50aWZpZXItbGRhcCIsImxnLnQiOiIxIiwic2NwIjoib3BlbmlkIiwic3ViIjoiVUY5RzJFOFFNS083RjdSNkBQZ3hDSGFaYVN4UHlydDdHNHI5SGxMUEtmemxsR19fdUVBaFpnclVXNE1xZndpNk1PVnQ1bW0xU3haQy0yeDlCWk9QMExBIn0.WokzneLSjMsiNwYAefo5Dw_Y3MVYGyfMYopbkCI3TihJ7LXUTZMeJg8AJ7B_TXqNnWgxsbRI6AxKjUFfHH1Dwrs2J3phyZAoJWywsiXGb_IwuprYiFZ4UhIYWolhb_CG_92CtMTFV0mieIlBKtTz9Nr3gZut5Dl6kMA83S3w7Ru3fOLUuUkrbF9yBSk4ZvOOx7HGqkRFOZZMgv5FBMiQVrhGeFi8GL4e2r_eGFFOYbU_BlIlXu20dkM4eP5p6ccN-SzrlbgtrVyDq2yWi1G7BJAUsAzMvlgetscQ2pf-_-pLW4TXTIJrV9PNYm38KR2lkWtFIvk_fhYWxtLKVKUmNloJZAH_CeCyO2POyCyo6mEttHsXGOnlivISYYdZLZd4P0h815jcsMphSOF62MPjBYL0tTSfRJ72lRnQvB4lgtHqb9zh__LUvhJaVxEqbZ896KJDw-Cql9Ax32ZUMRspQL-5Cs7lS67CSM0Uz3oAofSoD0SdjFXVkEFBfImrCDmh3OUeOK_jizmPFGI3NPGHtiyABXP4fDIufp1EMm7HmhtyxHNFOr9TUeErWgGSujXWM07Fuf1wE2C5hf30rEpHBMS-6Vxt438OkL2YkMmA18O1qm8sxXaPC5tGfhaQ5V5hy10JECeOvqGba06EzaghponWdA0rqhI0axS804g6PbA';
$newDirectoryName = "Testing";

$client = new Client([
    'baseUri' => $url,
    'accessToken' => $accessToken,
]);
// Access the underlying Sabre\HTTP\Client object
$httpClient = $client->getHttpClient();

// Access the underlying cURL handle and set the options
$curlHandle = $httpClient->getCurlHandle();
curl_setopt($curlHandle, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curlHandle, CURLOPT_SSL_VERIFYPEER, 0);

$response= $client->request('MKCOL', $newDirectoryName);
